### ISSUE TITLE
Update, please, to 1.37

### ISSUE THREAD

**Issue by hellGerra** [EnderdracheLP/QuestSounds#4]
### Is your feature request related to a problem?

:3

### Describe the solution you'd like

:3

### Describe alternatives you've considered

:3

### Device

Quest 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-r-elp** [comment]
The update is already being worked on in #3.
This issue will be closed once #3 is merged.

**Comment by michael-r-elp** [comment]
https://github.com/EnderdracheLP/QuestSounds/releases/tag/1.5.0
